name: RustDesk Host Setup

on:
  push:
    branches:
      - main

jobs:
  setup-rustdesk:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install RustDesk Host
      run: |
        Invoke-WebRequest -Uri "https://github.com/rustdesk/rustdesk/releases/latest/download/rustdesk-host.zip" -OutFile "rustdesk.zip"
        Expand-Archive -Path "rustdesk.zip" -DestinationPath "./rustdesk"

    - name: Configure RustDesk Host
      run: |
        New-Item -Path "C:\RustDesk\Config" -ItemType Directory -Force
        Set-Content -Path "C:\RustDesk\Config/host.toml" -Valu
"@

    - name: Start RustDesk
      run: |
        Start-Process -NoNewWindow -FilePath "C:\RustDesk\rustdesk.exe" -ArgumentList "--server"
