name: Temporary Windows RDP

on:
  push:
    branches:
      - main

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
      - name: Install RDP Tools
        run: |
          powershell -Command "Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force"
          powershell -Command "Install-WindowsFeature -Name Remote-Desktop-Services"
          powershell -Command "Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'"
      
      - name: Create RDP User
        run: |
          powershell -Command "net user github_user Password123! /add"
          powershell -Command "net localgroup administrators github_user /add"

      - name: Display RDP Connection Info
        run: |
          $IP = (Invoke-RestMethod http://ipinfo.io/json).ip
          Write-Host "Public IP: $IP"
          Write-Host "Username: github_user"
          Write-Host "Password: Password123!"
