# rustdesk-server.yml

# Configure the network
network:
  # Port for relay server
  relay_server:
    port: 21115
    bind: "0.0.0.0"  # Bind to all interfaces (you can specify your server IP here)
  # Port for rendezvous server
  rendezvous_server:
    port: 21116
    bind: "0.0.0.0"

# Logging
log:
  level: info
  file: "rustdesk.log"

# Enable HTTPS
https:
  enable: true
  cert_file: "/path/to/ssl/certificate.pem"
  key_file: "/path/to/ssl/key.pem"

# Monitoring (optional, you can adjust settings for monitoring purposes)
monitoring:
  enable: true
  port: 9090

# Config for users (you can add user permissions or other settings here)
users:
  - username: "admin"
    password: "securepassword123"
