name: RustDesk Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc

      # Install additional dependencies
      - name: Install dependencies
        run: |
          choco install -y cmake
          choco install -y mingw
          rustup component add rustfmt clippy

      # Build the project
      - name: Build RustDesk
        run: |
          cargo build --release

      # Archive the build output
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rustdesk-windows-build
          path: target/release/rustdesk.exe
